### ISSUE TITLE
Nova's proposal Test failed 

### ISSUE THREAD

**Issue by kxdemon** [nii-cloud/dodai-deploy#13]
After successful installation of "openstack nova diablo" Software, test failed

// Log's output:

info: Caching catalog for ostack-node2.gfi.su 
 info: Applying configuration version '1322480186' 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: rm: cannot remove `nova.zip': No such file or directory 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Archive: nova.zip 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: extracting: env/novarc 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: extracting: env/pk.pem 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: extracting: env/cert.pem 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: extracting: env/cacert.pem 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: default None None icmp -1 -1 0.0.0.0/0 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ApiError: {'to_port': -1, 'cidr': u'0.0.0.0/0', 'from_port': -1, 'protocol': 'icmp', 'parent_group_id': 1L} - This rule already exists in group 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: default None None tcp 22 22 0.0.0.0/0 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ApiError: {'to_port': 22, 'cidr': u'0.0.0.0/0', 'from_port': 22, 'protocol': 'tcp', 'parent_group_id': 1L} - This rule already exists in group 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Reading package lists... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Building dependency tree... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Reading state information... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: cloud-utils is already the newest version. 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: 0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded. 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: /tmp/nova/image_kvm.tgz 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ttylinux-uec-amd64-12.1_2.6.35-22_1-floppy 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ttylinux-uec-amd64-12.1_2.6.35-22_1.img 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ttylinux-uec-amd64-12.1_2.6.35-22_1-initrd 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ttylinux-uec-amd64-12.1_2.6.35-22_1-loader 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: ttylinux-uec-amd64-12.1_2.6.35-22_1-vmlinuz 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Encrypting image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Splitting image... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Part: kernel.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Generating manifest /tmp/kernel.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking bucket: mybucket 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading manifest file 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading part: kernel.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploaded image as mybucket/kernel.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Encrypting image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Splitting image... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Part: ramdisk.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Generating manifest /tmp/ramdisk.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking bucket: mybucket 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading manifest file 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading part: ramdisk.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploaded image as mybucket/ramdisk.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Encrypting image 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Splitting image... 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Part: image.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Part: image.part.01 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Generating manifest /tmp/image.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Checking bucket: mybucket 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading manifest file 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading part: image.part.00 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploading part: image.part.01 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Uploaded image as mybucket/image.manifest.xml 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: image: [<?xml] 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: euca-run-instances <?xml -k mykey -t m1.tiny 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Warning: failed to parse error message from AWS: <unknown>:2:66: unclosed token 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Traceback (most recent call last): 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/bin/euca-run-instances", line 246, in <module> 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: main() 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/bin/euca-run-instances", line 237, in main 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: euca.display_error_and_exit('%s' % ex) 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/lib/python2.7/dist-packages/euca2ools/**init**.py", line 1435, in display_error_and_exit 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: dom = minidom.parseString(msg) 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/lib/python2.7/xml/dom/minidom.py", line 1924, in parseString 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: return expatbuilder.parseString(string) 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: return builder.parseString(string) 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: parser.Parse(string, True) 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: xml.parsers.expat.ExpatError: unclosed token: line 1, column 87 
 notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: Executing command euca-run-instances failed. 
 err: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: change from notrun to 0 failed: /tmp/nova/test.sh image_kvm.tgz nova admin 2>&1 returned 1 instead of one of [0] at /etc/puppet/manifests/packages/nova.pp:143 
 notice: Finished catalog run in 66.16 seconds

//------------------------------------

// OS Ubuntu 11.04

/\* Config items */

network_ip_range    10.0.0.0/24
libvirt_type    kvm
glance_host 169.254.0.1
user    admin
password    admin
email   admin@openstack.org
project nova
dashboard_port  8000

/\* Node configs */

// ostack-node2.gfi.su:

dashboard_r46
mysql
nova_api
nova_compute
nova_network
nova_objectstore
nova_scheduler
nova_volume
rabbitmq

/\* Component configs */

// dashboard_r46
// local_settings.py:

import os 

DEBUG = True 
TEMPLATE_DEBUG = DEBUG 
PROD = False 
USE_SSL = False 

LOCAL_PATH = os.path.dirname(os.path.abspath(**file**)) 
DATABASES = { 
    'default': { 
        'ENGINE': 'django.db.backends.sqlite3', 
        'NAME': os.path.join(LOCAL_PATH, 'dashboard_openstack.sqlite3'), 
    }, 
} 

CACHE_BACKEND = 'dummy://' 
# Configure these for your outgoing email host
# EMAIL_HOST = 'smtp.my-company.com'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'djangomail'
# EMAIL_HOST_PASSWORD = 'top-secret!'

NOVA_DEFAULT_ENDPOINT = 'http://<%= nova_api %>:8773/services/Cloud' 
NOVA_DEFAULT_REGION = 'nova' 
NOVA_ACCESS_KEY = os.environ.get("EC2_ACCESS_KEY", "") 
NOVA_SECRET_KEY = os.environ.get("EC2_SECRET_KEY", "") 
NOVA_ADMIN_USER = '<%= user %>' 
NOVA_PROJECT = '<%= project %>'

// nova_compute

/etc/nova/nova-compute.conf --libvirt_type=<%= libvirt_type %>

/\* Software configs */
// /etc/nova/nova.conf:

--sql_connection=mysql://root:nova@<%= mysql %>/nova 

--s3_host=<%= nova_objectstore %> 

--rabbit_host=<%= rabbitmq %> 
--cc_host=<%= nova_api %> 
--ec2_url=http://<%= nova_api %>:8773/services/Cloud 

--daemonize=1 

--dhcpbridge_flagfile=/etc/nova/nova.conf 
--dhcpbridge=/usr/bin/nova-dhcpbridge 

--FAKE_subdomain=ec2 

--ca_path=/var/lib/nova/CA 
--keys_path=/var/lib/nova/keys 
--networks_path=/var/lib/nova/networks 
--instances_path=/var/lib/nova/instances 
--images_path=/var/lib/nova/images 
--buckets_path=/var/lib/nova/buckets 

--vlan_interface=eth1 
--flat_interface=eth1 
--volume_group=<%= nova_volume %> 

--network_manager=nova.network.manager.VlanManager 

--libvirt_type=<%= libvirt_type %> 

--glance_api_servers=<%= glance_host %>:9292 

--image_service=nova.image.glance.GlanceImageService 

--lock_path=/var/lib/nova/tmp 
--logdir=/var/log/nova 
--verbose 
--use_deprecated_auth=true

// EOF

May you help me to correct  this issue ?
May be i did something wrong...

**Comment by guanxiaohua2k6** [comment]
It seems that it failed to register the image due to the following error messages.

> notice: /Stage[main]/Nova_api::Test/Exec[/tmp/nova/test.sh image_kvm.tgz nova admin 2>&1]/returns: image: [<?xml] 

Where "<?xml" in "image: [<?xml]" should be image id, something like ami-0000003. It may be related with glance. Have you installed glance already? And can you provide contents of /var/log/nova/nova-api.log and /var/log/nova/nova-objectstore.log and  /var/log/glance/*.log?

**Comment by kxdemon** [comment]
"Have you installed glance already?" - Yes, I have installed glance onto another node.

"And can you provide contents of /var/log/nova/nova-api.log and /var/log/nova/nova-objectstore.log and /var/log/glance/*.log?" - I sent you log files by email.

**Comment by guanxiaohua2k6** [comment]
I found the following error message int the nova-api.log.

(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/glance/registry/server.py", line 309, in create
(nova.api): TRACE:     image_data = db_api.image_create(req.context, image_data)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/glance/registry/db/api.py", line 107, in image_create
(nova.api): TRACE:     return _image_update(context, values, None, False)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/glance/registry/db/api.py", line 369, in _image_update
(nova.api): TRACE:     image_ref.save(session=session)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/glance/registry/db/models.py", line 55, in save
(nova.api): TRACE:     session.flush()
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1359, in flush
(nova.api): TRACE:     self._flush(objects)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1440, in _flush
(nova.api): TRACE:     flush_context.execute()
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 299, in execute
(nova.api): TRACE:     rec.execute(self)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 443, in execute
(nova.api): TRACE:     uow
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1863, in _save_obj
(nova.api): TRACE:     execute(statement, params)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1194, in execute
(nova.api): TRACE:     params)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1274, in _execute_clauseelement
(nova.api): TRACE:     return self.__execute_context(context)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1305, in __execute_context
(nova.api): TRACE:     context.parameters[0], context=context)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1404, in _cursor_execute
(nova.api): TRACE:     context)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1397, in _cursor_execute
(nova.api): TRACE:     context)
(nova.api): TRACE:   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 299, in do_execute
(nova.api): TRACE:     cursor.execute(statement, parameters)
(nova.api): TRACE: OperationalError: (OperationalError) unable to open database file u'INSERT INTO images (created_at, updated_at, deleted_at, deleted, name, disk_format, container_format, size, status, is_public, location, checksum, min_disk, min_ram, owner) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('2011-11-29 07:15:37.346431', None, None, False, None, u'ari', u'ari', 0, u'queued', False, None, None, 0, 0, None)

It seems that it failed to add a record to images table of glance when registering a image. So the error should be something related to the configuration of glance. Which DBMS are you using? Now, we just support sqlite only for glance.

**Comment by kxdemon** [comment]
I found my mistake in configuration of nova, I specified another IP address of glance_host on another interface, because two nodes are directly connected between themselves.

**Comment by guanxiaohua2k6** [comment]
Have you solved the problem?

**Comment by kxdemon** [comment]
Yes, test was successful
