### ISSUE TITLE
Node not visible

### ISSUE THREAD

**Issue by metakermit** [nii-cloud/dodai-deploy#19]
I'm experiencing a problem with my 8-node setup that I'm trying to control using dodai-deploy. One of the slave nodes doesn't appear on the "add node" list in the web interface of the master node. It also isn't listed when I issue:

ruby script/cli.rb <master> node_candidate list

All the other slave nodes are working correctly and are showing up on the web interface. I installed the dodai-deploy client  to all the same slave nodes the same way (using cluster-ssh) and I can ping in both direction between the master and the troublesome slave node. This is the nmap output for the troublesome node (excluding the details of the ip and hostname, which appear to be fine):

rDNS record for xx.xx.xx.xx: <troublesome node hostname>
Not shown: 997 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
111/tcp  open  rpcbind
2049/tcp open  nfs

Do you have any idea how I might go on debugging the problem? Is there some way to test that the slave daemon is running OK?

**Comment by guanxiaohua2k6** [comment]
Could you confirm the time of the master node and troublesome node with the following command?

```
date -u
```

If they are different, pls change the time of troublesome node, and then restart mcollective with the following command.

```
service mcollective restart
```

**Comment by metakermit** [comment]
Thanks for your help, Xiaohua! The time was indeed out of sync so I've set
up all the nodes' ntp daemons to look at the master node's time following this
tutorial https://help.ubuntu.com/community/UbuntuTime. Now it works and I
see all the nodes through the web interface :)

Cheers,
Dražen

On Wed, Jul 11, 2012 at 3:23 AM, Xiaohua Guan <
reply@reply.github.com
