### ISSUE TITLE
nova-api should be installed last in the nova proposal

### ISSUE THREAD

**Issue by metakermit** [nii-cloud/dodai-deploy#21]
After running into some problems with nova-api's meta-data server and UEC guest VMs being unable to import public keys from it, it seems one has to restart the nova-api service for the meta-data server to configure correctly.

I was doing a 1-node all-default dodai-deploy install of OpenStack so after consulting some of the folks at #openstack, we suspect the issue might be with nova-api being installed before nova-compute - nova-api should be installed last. To quote a kind person who helped me fixed my problem:

```
zynzel 15:07:34
kermit666: my idea is that you install nova-compute after nova-api
so nova-api was starting before compute so it dont start metadata-api
but this is my guess
```

I posted a more detailed [problem and solution description at AskUbuntu.](http://askubuntu.com/questions/165115/ubuntu-cloud-instances-in-openstack-cant-import-public-ssh-key)

**Comment by guanxiaohua2k6** [comment]
Thank you for your information. I hacked the code of nova, and found that it seems a bug of nova essex. I've reported the bug. Please see the following page for your reference.

https://bugs.launchpad.net/nova/+bug/1026464

**Comment by metakermit** [comment]
OK, thanks. I've also marked myself as being affected and am monitoring
that thread now.

Cheers,
Dražen

On Thu, Jul 19, 2012 at 8:51 AM, Xiaohua Guan <
reply@reply.github.com

**Comment by guanxiaohua2k6** [comment]
The bug 1026464 I reported duplicated with https://bugs.launchpad.net/nova/+bug/1002111. And it was fixed in folsom.
