### ISSUE TITLE
Error Installing Folscom Swift on Ubuntu 12.04

### ISSUE THREAD

**Issue by jravetch** [nii-cloud/dodai-deploy#34]
I get the following error when trying to install Folsom Swift:

info: Loading facts in /etc/puppet/modules/apt/lib/facter/apt_version.rb 
info: Caching catalog for cn01040804.ecloud.nii.ac.jp 
info: Applying configuration version '1353906220' 
notice: /Stage[main]/Swift_f::Common/File[/etc/swift/cert.crt]/ensure: defined content as '{md5}80e307e35b94689794f6bdfdf2edcba9' 
notice: /Stage[main]/Swift_f::Common/File[/etc/swift/cert.key]/ensure: defined content as '{md5}2647a92f16f9b6ec3b75dc4cb1dabe9a' 
notice: /Stage[main]/Swift_f::Common/File[/etc/swift/swift.conf]/ensure: defined content as '{md5}92a37059ce0675c373c4292054d50b81' 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Package[swift]/ensure: ensure changed 'purged' to 'present' 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Package[swift-proxy]/ensure: ensure changed 'purged' to 'present' 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/File[/etc/swift/proxy-server.conf]/ensure: defined content as '{md5}bbe923b2e959d1e9907393e05c660276' 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Package[swauth]/ensure: ensure changed 'purged' to 'present' 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: No proxy-server running 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Device z1-136.187.33.85:6002/sdb1_"" with 100.0 weight got id 0 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Device z1-136.187.33.85:6001/sdb1_"" with 100.0 weight got id 0 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Device z1-136.187.33.85:6000/sdb1_"" with 100.0 weight got id 0 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Reassigned 262144 (100.00%) partitions. Balance is now 0.00. 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Reassigned 262144 (100.00%) partitions. Balance is now 0.00. 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Reassigned 262144 (100.00%) partitions. Balance is now 0.00. 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Starting proxy-server...(/etc/swift/proxy-server.conf) 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: Traceback (most recent call last): 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: File "/usr/bin/swift-proxy-server", line 22, in <module> 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: run_wsgi(conf_file, 'proxy-server', default_port=8080, **options) 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: File "/usr/lib/python2.7/dist-packages/swift/common/wsgi.py", line 126, in run_wsgi 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: log_to_console=kwargs.pop('verbose', False), log_route='wsgi') 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 608, in get_logger 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: raise e 
notice: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: socket.error: [Errno 111] Connection refused 
err: /Stage[main]/Swift_f::Swift_proxy::Install/Exec[/tmp/swift/proxy-init.sh sdb1 1 2>&1]/returns: change from notrun to 0 failed: /tmp/swift/proxy-init.sh sdb1 1 2>&1 returned 1 instead of one of [0] at /etc/puppet/modules/swift_f/manifests/swift_proxy/install.pp:29 
notice: Finished catalog run in 26.57 seconds 

Any support would be greatly appreciated.

**Comment by guanxiaohua2k6** [comment]
Firstly, I did the same thing in my environment, it is OK. 

Then, I viewed the relevant code, it may be caused by the reason that the device /dev/log didn't exist. Could you confirm it?

As to how to solve problem the device /dev/log didn't exist, it can be solved by installing rsyslog.

**Comment by jravetch** [comment]
@guanxiaohua2k6 Yes I can confirm /dev/log doesn't exist.  However, syslog-ng is installed instead of rsyslog.  Should i replace syslog-ng with rsyslog?

**Comment by guanxiaohua2k6** [comment]
It's OK to use syslog-ng instead of rsyslog. But you should change the /etc/syslog-ng.conf to make it use /dev/log.

**Comment by jravetch** [comment]
Here is what's already configured in /etc/syslog-ng/syslog-ng.conf.  I believe dodai-deploy is already configuring syslog-ng.

sysope@cn01040804:/dev$ cat /etc/syslog-ng/syslog-ng.conf
options {
   sync(0);
   time_reopen(10);
   log_fifo_size(1000);
   long_hostnames(off);
   use_dns(no);
   use_fqdn(no);
   create_dirs(no);
   keep_hostname(yes);
   stats(3600);
};

source s_local {
   file("/proc/kmsg" log_prefix("kernel: "));
   unix-stream("/dev/log");
   internal();
};

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/syslog"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" sync(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_mlal { usertty("*"); };

filter f_mesg { level(info..emerg) and not facility(mail,authpriv,cron); };
filter f_auth { facility(authpriv); };
filter f_mail { facility(mail); };
filter f_mlal { level(emerg); };
filter f_spol { facility(uucp) or (facility(news) and level(crit..emerg)); };
filter f_boot { facility(local7); };
filter f_cron { facility(cron); };

log { source(s_local); filter(f_mesg); destination(d_mesg); };
log { source(s_local); filter(f_auth); destination(d_auth); };
log { source(s_local); filter(f_mail); destination(d_mail); };
log { source(s_local); filter(f_mlal); destination(d_mlal); };
log { source(s_local); filter(f_spol); destination(d_spol); };
log { source(s_local); filter(f_boot); destination(d_boot); };
log { source(s_local); filter(f_cron); destination(d_cron); };

source s_dodai_instance_agent { file("/var/log/dodai/dodai-instance-agent.log"); };
filter f_dodai_instance_agent { level(warn); };
log { source(s_dodai_instance_agent); filter(f_dodai_instance_agent); destination(d_mesg); };

filter f_hinemos_log { level(err..emerg); };
source s_netudp { udp(ip(127.0.0.1) port(514)); };
log { source(s_netudp); filter(f_hinemos_log); destination(d_hinemos);};
destination d_hinemos { tcp("10.11.254.1" port(514));};
log { source(s_local);filter(f_hinemos_log);destination(d_hinemos);};

**Comment by guanxiaohua2k6** [comment]
Could you confirm whether the service syslog-ng is started or not?

**Comment by jravetch** [comment]
syslog-ng wasn't started, so I tried to start it and got the following error:

sysope@cn01040804:/dev$ sudo service syslog-ng status
[sudo] password for sysope: 
- syslog-ng is not running
  sysope@cn01040804:/dev$ sudo service syslog-ng start
- Starting system logging syslog-ng                                                                                            WARNING: Configuration file has no version number, assuming syslog-ng 2.1 format. Please add @version: maj.min to the beginning of the file;
  WARNING: Configuration file format is too old, please update it to use the 3.3 format as some constructs might operate inefficiently;
  WARNING: global: the default value of chain_hostnames is changing to 'no' in version 3.0, please update your configuration accordingly;
  WARNING: global: the default value of log_fifo_size() has changed to 10000 in version 3.3 to reflect log_iw_size() changes for tcp()/udp() window size changes;
  Your configuration file uses an obsoleted keyword, please update your configuration; keyword='sync', change='flush_lines'
  Your configuration file uses an obsoleted keyword, please update your configuration; keyword='long_hostnames', change='chain_hostnames'
  Your configuration file uses an obsoleted keyword, please update your configuration; keyword='stats', change='stats_freq'
  WARNING: input: sources do not remove new-line characters from messages by default in version 3.0, please add 'no-multi-line' flag to your configuration if you want to retain this functionality;
  WARNING: file source: default value of follow_freq in file sources is changing in 3.0 to '1' for all files except /proc/kmsg;
  Your configuration file uses an obsoleted keyword, please update your configuration; keyword='log_prefix', change='program_override'
  WARNING: the expected message format is being changed for unix-domain transports to improve syslogd compatibity with syslog-ng 3.2. If you are using custom applications which bypass the syslog() API, you might need the 'expect-hostname' flag to get the old behaviour back;
  WARNING: template: the default value for template-escape is changing to 'no' in version 3.0, please update your configuration file accordingly;
  Unable to determine how to monitor this fd, follow_freq() not set and it is not possible to poll it with the current ivykis polling method, try changing IV_EXCLUDE_POLL_METHOD environment variable; fd='10'
  Error initializing log_reader, closing fd; fd='10'
  Error initializing source driver; source='s_dodai_instance_agent', id='s_dodai_instance_agent#0'
  Error initializing message pipeline;
                                                                                                                       [fail]

**Comment by guanxiaohua2k6** [comment]
If you are using NII academic cloud, the service syslog-ng should be started after the instance booted.

Regarding the question, because it is related to the image created by NII, I think it's better to ask NII why the service syslog-ng couldn't started after the instance booted.

**Comment by jravetch** [comment]
@guanxiaohua2k6 I confirmed the issue was the syslog-ng conf and it was customized for 11.10 not 12.04, which uses syslog-ng 3.3, so syslog-ng was not starting correctly.  I modified the config to use 3.3 syntax and was able to start syslog-ng service.  I then was able to successfully install swift.  Thanks again for your help.

**Comment by guanxiaohua2k6** [comment]
I see. Thank you for your reply.
